before_script:
- cp .env.example .env
- bundle exec rake db:create
- bundle exec rake db:schema:load
bundler_args: --without production --deployment --jobs=3 --retry=3
cache: bundler
deploy:
  after_deploy:
  - rake db:migrate
  - restart
  - rake cleanup
  api_key:
    secure: "FCn11XFfho0K/nQU10K4Jhc2TXQeSeoXpdIuxmIBj9DONk/NtKd1Jx9H1OfkGt3DGhFB1qIhN1i35SylU9jmsua3yfwkzTXyCpOuqp84eCsgz+aJazd97BRDs2O+LDH1+M4bDTw+LnQ8RLJNe62a/nBLEUuC1RABAjI8mezzbKg="
  app: atthemovies
  before_deploy:
  - git stash
  - pg:backups capture
  clean_up: false
  on:
    branch: master
  provider: heroku
  strategy: git
language: ruby
notifications:
  email: false
  slack:
    on_failure: always
    on_success: always
    secure: "C7U6G5pydNqjnfO7ee7fWf1toDX8cKP/SN6ziunvyNIx+wJF60LgYi/TwKDkwh4MRDmFSVsVBLX0+XUmVwOpmktYSQ64UWym0iqvqRebDJ/hCjbMZCpurnyQ1nQM4xaKNR5JxUm5doldRLZIVOnDRy15OEq+ccb7KSpL+Vt23cQ="
rvm:
- 2.3.0
script: bundle exec rspec
