before_script:
- cp .env.example .env
- bundle exec rake db:create
- bundle exec rake db:schema:load
bundler_args: --without production --deployment --jobs=3 --retry=3
cache: bundler
deploy:
  api_key:
    secure: "zr12X6DHqlS6qX2PMZ+X+FbguVzoVT+NkiKzbJzKkD066EHJ/HGDr4sVpTwaz09IHPzEqTO0pXJFXpT+mflZU1fDTgZFR8x3Ad91bvsIBvofWSNWwZ+GM+V/5dcw8vnsVGmnpiFGH5NTKmPe07jvr328fNVnnZ2LMeZbwoaoyDtMXwbynvz0GEyv2DhDWYFh46vNQg3W4gil+IxzAm07gr0LN7JEF/wtv6Nz+VFsYb1TgjwLARw+3hNn3UgX/ygSXcbYJYYyEvYaZCNaUZ3f3+LDJrDydEV5OtFhnn+YD7MpGf9wmtPG1B80J1t+86y/J/xHcVRFiQeOgaXfjccTdkbM5CQ917z525toBQAeRYKKn6Tzx0tsmPiD8I2OW1OKFJtsiogKNRcz2xZXIYhf7TjERLzoiI1KPCxkofwqbvFMfa2RAtVbtBXeVN7lrRoXR11Dwh13/FxuIMjuYrizKSnKP/bcZ7Vg3ED4pisG77JdbHw0e5rwFORZk1ty/SXn0bdFbGCYh1778Hv9JnkvuYtQthGEJ4uKnPQagbZiZ409WYEhqN7bFXlnSMadCEidy7WtpgJ9rMvK+z1Pk4YpPOfZomeDsdOl+oJHa8b6OnJ+tWrEuz5WY5EAXLnHVzOKxA0jt5gnJeQmA2678PoP8TxbJ46kitnkTXE/20TKayg="
  app: atthemovies
  on:
    branch: master
  provider: heroku
  run:
  - pg:backups capture
  - rake db:migrate
  - restart
language: ruby
notifications:
  email: false
  slack:
    on_failure: always
    on_success: always
    rooms:
      secure: "CDqfILIJ0YaqxvUZF0OKhSbjKEF4FP+pfvGkrEq2piQLbWWwEeHjeaxjm5Bcv/16oa3uikkeEGUKZ7K02BA1kmOyTpg8n5wEEpFKmPI2PogC3VIS+rmA8TGqGnktuHiLDZcMBzjxkNvqzVwQSW+uVorkb+KV7ZN+aEGoC+JRM2Jdu3c6Uwj2XDNRZEcGluB8/22KmUAZGzhv6BHFJLubnWpUIdpIiUbClDjqzCyDxOaAh8fAnfen1cPltOX0AnMUSV/zxJQNT0S/gGPGmeUaf/ej92KRujBrauYHkvD7ocbnkjhRi8rfj5wQI2Yhw+Uh3yT2GWVUY6/ThdW06I5cdJW0+T5p4svAyyHs4FQTPvDELZ6hKahZJNihrJATb74mKS8FdWeWRR175KuwUwNoKfUCbtd4gQhvU+6Yto+hSUHkAdICdT5r7QNtIZ7uUxGhGADW9aV/UJ/6KdSZHr2Qbw0oJ1c5eC5r5InjmE43djXB5qCHa2TDik4HghoeYEII2xzJ4St1Bh2AMY88RCRGP+zEVU9vnIRNyL6qrCPA+5LJitBLBSw6ZbKAMOBl6NeF8F1DOSenmtlGEco3Uy10zKYNYzDwsjasNLAocyIMY9eEezorKEhGSV+xmtukkkU3l/JzgMxdfukuVOwV2U+gA1tMsSrYjgBFs4hC5JM1sZ4="
rvm:
- 2.3.0
script: bundle exec rspec
