before_script:
- cp .env.example .env
- bundle exec rake db:create
- bundle exec rake db:schema:load
bundler_args: "--without production"
deploy:
  after_deploy:
  - rake db:migrate
  - restart
  - rake cleanup
  api_key:
    secure: jtRdYaxDmsevBXiAVgOnemUIi89c0m4dRZF7OhY64cnOQELavdYKABnLKiMNJ+9o+aaA4a371WdCVPHDsdjRWzQR7qI5nLn3EnXB6DT/N0hITof1lEVO13dStfKphsIKSqgHIKWdULCAyXS7isxT5SRpOi4soMCL+3z/1jEWcHk=
  app: atthemovies
  before_deploy:
  - git stash
  - pg:backups capture
  on:
    branch: master
  provider: heroku
  strategy: git
language: ruby
notifications:
  email: false
  slack:
    on_failure: always
    on_success: always
    secure: LzKkLVP1nOb90ZOURIIVL+dFIGYyXAYALsvqJZiyDXMBvjnd0i/2zg+ZHGer1/Xks8x/SZNFpAA4EUE9MPhqb9t8rLDsldpk8UyR9umlI3XJETp/qO0MXanIAyvXeRl09+t8yGzH6tkOwM42k1u6eVpFf9oq3pr5s5waWapOoLE=
rvm:
- 2.3.0
script: bundle exec rspec
