Crawler::CUSTOM << Crawler.new(:apple, 'Applebot')
Crawler::CUSTOM << Crawler.new(:arefs, 'AhrefsBot')
Crawler::CUSTOM << Crawler.new(:mailru, 'Mail.RU_Bot')
Crawler::CUSTOM << Crawler.new(:magestic12, 'MJ12bot')
Crawler::CUSTOM << Crawler.new(:seznam, 'SeznamBot')
